<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>cb18d568-add2-4ef2-bc1e-c4745d6f698c</testSuiteGuid>
   <testCaseLink>
      <guid>2a5c8e06-9561-43ef-ada0-c87421238533</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day2/Test_DataDrivenDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>afc02354-cda4-4766-a77b-4b4b69bd2bf3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataForLoginTest</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>afc02354-cda4-4766-a77b-4b4b69bd2bf3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>28557b1e-b973-4152-9b6d-0497b9a68504</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>afc02354-cda4-4766-a77b-4b4b69bd2bf3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>8799a333-ee39-4168-8962-470b70d6c113</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
